# prod env
FROM node:13-alpine
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
RUN npm install --silent
RUN npm install react-scripts -g --silent
COPY . /app
RUN npm run build

RUN npm install -g serve
RUN serve -s build
EXPOSE 3000
# Inicializa a aplicação
CMD ["npm", "start"]